export const Quotes = [
  "Everything happening around me is very random. I am enjoying the phase, as the journey is far more enjoyable than the destination. - Sushant Singh Rajput",
  "Self-belief and hard work will always earn you success. - Virat Kohli",
  "If you spend time with your loved ones, you get the energy to do your job better. - Sushant Singh Rajput",
  "Success is not a good teacher, failure makes you humble. - Shah Rukh Khan",
  "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "Be yourself; everyone else is already taken. — Oscar Wilde",
  "In the middle of difficulty lies opportunity. — Albert Einstein",
  "Do what you can, with what you have, where you are. — Theodore Roosevelt",
  "Happiness is not by chance, but by choice. — Jim Rohn",
  "Live what you love. — Anonymous",
  "Stay hungry, stay foolish. — Steve Jobs",
  "Life is what happens when you're busy making other plans. — John Lennon",
  "Believe you can and you're halfway there. — Theodore Roosevelt",
  "Time flies over us, but leaves its shadow behind. — Nathaniel Hawthorne",
  "The best is yet to come. — Frank Sinatra",
];
